// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEj8rKTtAsptc3YR08dNTVAE2gS3w_JLk',
    appId: '1:536050001058:web:cf775f74c9c3c163e423fb',
    messagingSenderId: '536050001058',
    projectId: 'fir-t1-4f2c7',
    authDomain: 'fir-t1-4f2c7.firebaseapp.com',
    storageBucket: 'fir-t1-4f2c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlZKcezC2wRFsTjeFX9otLZQIg2mcMP8',
    appId: '1:536050001058:android:5c96af807889b31fe423fb',
    messagingSenderId: '536050001058',
    projectId: 'fir-t1-4f2c7',
    storageBucket: 'fir-t1-4f2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SBsZ-VFPSmDALmpme09pbRTNMRUJkxY',
    appId: '1:536050001058:ios:11aeb60107f37963e423fb',
    messagingSenderId: '536050001058',
    projectId: 'fir-t1-4f2c7',
    storageBucket: 'fir-t1-4f2c7.firebasestorage.app',
    iosBundleId: 'com.example.voiceIotApp',
  );

}